/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import Dado.*;
import Tablero.*;
/**
 **
 ** @author Luis Alonso Corella Chaves
 ** @author Carlos Daniel Martines Sequeira * 16/10/2017
 */
public class Frm_Inicio extends javax.swing.JFrame {
    /**
     * Creates new form P_View
     */
    private Tablero tablero;
    public Frm_Inicio() {
        initComponents();
        setLocationRelativeTo(null);
        tablero = new Tablero();
        btnInicio.setVisible(false);
        imagenes1 objImag2 = new imagenes1();
        lblDado.setIcon(objImag2.gifDado1(1));
        btnExit.setContentAreaFilled(false);
        btnExit.setBorder(null);
    }
    public void irAFrmJuego(){
        Frm_Juego j = new Frm_Juego(tablero);
        j.setVisible(true);
        j.setLocationRelativeTo(null);
        dispose();
    }
    public void verificarInicio(){
        if (tablero.getPartida().verificarInicio(txtJugador1.getText(), txtJugador2.getText())) {
            if(tablero.getPartida().verificarIgualdadDeJugadores(txtJugador1.getText().trim().toLowerCase()
                    , txtJugador2.getText().trim().toLowerCase())){
                generarNum();
                btnInicio.setVisible(true);
            }else{
                lblMensaje.setText("El nombre de los jugadores son iguales.");
            }
        } else {
            lblMensaje.setText("Debes digitar el nombre de ambos jugadores.");
        }
    }
    public void generarNum() {
        generanumero objDado = new generanumero();
        int dados = objDado.calculanumero();
        imagenesResul objImag1 = new imagenesResul();
        lblDado.setIcon(objImag1.Imaen(dados));
        elegirganador(dados);
    }
    public void elegirganador(int num) {
        tablero.getPartida().setJugador1(txtJugador1.getText());
        tablero.getPartida().setJugador2(txtJugador2.getText());
        if (num % 2 == 0) {
            lblResultado.setText("El ganador es el jugador: " + tablero.getPartida().getJugador1());
        } else {
            lblResultado.setText("El ganador es el jugador: " + tablero.getPartida().getJugador2());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtJugador1 = new javax.swing.JTextField();
        txtJugador2 = new javax.swing.JTextField();
        lblMensaje = new javax.swing.JLabel();
        lblDado = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblImagenDeFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(232, 35, 0));
        jLabel1.setText("AJEDREZ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(232, 35, 0));
        jLabel2.setText("Jugador 1:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(232, 35, 0));
        jLabel3.setText("Jugador 2:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, -1));

        txtJugador1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtJugador1.setForeground(new java.awt.Color(232, 35, 0));
        jPanel1.add(txtJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 205, -1));

        txtJugador2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtJugador2.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(txtJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 205, -1));

        lblMensaje.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(204, 7, 14));
        lblMensaje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 361, 37));

        lblDado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblDadoMousePressed(evt);
            }
        });
        jPanel1.add(lblDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 257, 197));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(232, 35, 0));
        jLabel5.setText("Impares");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(232, 35, 0));
        jLabel6.setText("Pares");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        lblResultado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(232, 35, 0));
        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 255, 370, 21));

        btnInicio.setBackground(new java.awt.Color(255, 255, 255));
        btnInicio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(232, 35, 0));
        btnInicio.setText("Iniciar Juego");
        btnInicio.setFocusable(false);
        btnInicio.setOpaque(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        jPanel1.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, -1, -1));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close.png"))); // NOI18N
        btnExit.setOpaque(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 51, 55));

        lblImagenDeFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoPrincipal.jpg"))); // NOI18N
        jPanel1.add(lblImagenDeFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        irAFrmJuego();
    }//GEN-LAST:event_btnInicioActionPerformed
    private void lblDadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDadoMousePressed
        if(tablero.getPartida().isBus()){
            verificarInicio();
        }
    }//GEN-LAST:event_lblDadoMousePressed
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Inicio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDado;
    private javax.swing.JLabel lblImagenDeFondo;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtJugador1;
    private javax.swing.JTextField txtJugador2;
    // End of variables declaration//GEN-END:variables
}
